# -*- coding: utf-8 -*-
"""RevouSimulasi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wMrUAHBIA52i0qOQoSUP7IhpqoGwuqId
"""

import pandas as pd

transaction = pd.read_csv('Transaction.csv')

transaction.head(10)

transaction.info()

transaction_backup = transaction.copy

transaction_backup

transaction['Transaction_id'] = transaction['Transaction_id'].astype('str')

transaction['customer_id'] = transaction['customer_id'].astype('str')

transaction['Date'] = pd.to_datetime(transaction['Date'], format='%m/%d/%Y')

transaction['Amount US$']

transaction['Amount US$'] = transaction['Amount US$'].str.replace(',','')

transaction['Amount US$'] = transaction['Amount US$'].astype('int')

transaction = transaction.dropna(axis=0)

transaction['Individual_Price_US$'] = transaction['Individual_Price_US$'].str.replace(',','')

transaction['Individual_Price_US$'].unique()

transaction['Individual_Price_US$'] = transaction['Individual_Price_US$'].astype('int')

"""menghapus #VALUE!"""

transaction = transaction[transaction['Individual_Price_US$']!='#VALUE!']

transaction.drop_duplicates()

transaction.to_csv('transaction1.csv')

from google.colab import files
files.download('transaction1.csv')